admin:
    resource: "@AppBundle/Controller/Admin"
    type:     annotation
    prefix:   /admin

pub:
    resource: "@AppBundle/Controller/Publik"
    type:     annotation

app:
    resource: "@AppBundle/Controller/User"
    type:     annotation
    prefix:   /app

pay:
    resource: "@AppBundle/Controller/Payment"
    type:     annotation

payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

payum_authorize:
    resource: "@PayumBundle/Resources/config/routing/authorize.xml"

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"