admin:
    resource: "@AppBundle/Controller/Admin"
    type:     annotation
    prefix:   /admin

pub:
    resource: "@AppBundle/Controller/Publik"
    type:     annotation

app:
    resource: "@AppBundle/Controller/User"
    type:     annotation
    prefix:   /app

goo:
    resource: "@AppBundle/Controller/GoogleMaps"
    type:     annotation
    prefix:   /

exp:
    resource: "@AppBundle/Controller/Export"
    type:     annotation
    prefix:   /

user_login_check:
    pattern:  app/login-check
user_logout:
    pattern:  app/logout

admin_login_check:
    pattern:  admin/login-check
admin_logout:
    pattern:  admin/logout

pay:
    resource: "@AppBundle/Controller/Payment"
    type:     annotation

payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

payum_authorize:
    resource: "@PayumBundle/Resources/config/routing/authorize.xml"

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"