admin:
    resource: "@AppBundle/Controller/Admin"
    type:     annotation
    prefix:   /admin

pub:
    resource: "@AppBundle/Controller/Publik"
    type:     annotation

app:
    resource: "@AppBundle/Controller/User"
    type:     annotation
    prefix:   /app

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"