security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        users:
            entity: { class: AppBundle\Entity\User, property: username }
    encoders:
        AppBundle\Entity\User:
            algorithm: plaintext
        Symfony\Component\Security\Core\User\User: 
            algorithm: plaintext

    firewalls:
        secured_area_users:
            pattern:    ^/app
            anonymous: ~
            form_login:
                check_path: user_login_check
                login_path: user_login
                default_target_path: user_home
                always_use_default_target_path: true
                provider: users
            logout:
                path:   user_logout
                target: user_login

    access_control:
        - { path: ^/app/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/app, roles: ROLE_USER }