security:

    role_hierarchy:
        ROLE_PAID:       ROLE_USER

    providers:
        my_custom_hwi_provider:
            id: hwi_oauth.user.provider.entity
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            oauth:
                resource_owners:
                    twitter:       twitter_login
                login_path:        home
                failure_path:      home

                oauth_user_provider:
                    service: hwi_oauth.user.provider.entity

    access_control:
        - { path: ^/home, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }