security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        admins:
            memory:
                users:
                    klipa:  { password: klipa, roles: [ 'ROLE_ADMIN' ] }
        users:
            entity: { class: AppBundle\Entity\User, property: username }
    encoders:
        AppBundle\Entity\User:
            algorithm: plaintext
        Symfony\Component\Security\Core\User\User: 
            algorithm: plaintext

    firewalls:
        secured_area_users:
            pattern:    ^/app
            anonymous: ~
            form_login:
                check_path: user_login_check
                login_path: user_login
                default_target_path: user_home
                always_use_default_target_path: true
                provider: users
            logout:
                path:   user_logout
                target: user_login
        secured_area_admins:
            pattern:    ^/admin
            anonymous: ~
            form_login:
                check_path: admin_login_check
                login_path: admin_login
                default_target_path: admin_home
                always_use_default_target_path: true
                provider: admins
            logout:
                path:   admin_logout
                target: admin_login

    access_control:
        - { path: ^/app/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/app, roles: ROLE_USER }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }