# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    payum.buzz.client:
        class: Buzz\Client\ClientInterface
        factory_class: Payum\Core\Bridge\Buzz\ClientFactory
        factory_method: createCurl
        calls:
            - [setVerifyPeer, [false]]
    my.listener:
        class: AppBundle\EventListener\EntityListener
        arguments:  [@service_container]
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    hwi_oauth.user.provider.entity:
        class: AppBundle\Provider\Provider
        arguments: [@session, @doctrine, @admin.checker, @request_stack]
    admin.checker:
        class: AppBundle\Provider\AdminChecker
        arguments: [@doctrine]