AppBundle\Entity\QueryJob:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    start_date:
      type: datetime
      nullable: true
    end_date:
      type: datetime
      nullable: true
  oneToMany:
    query:
      targetEntity: Query
      mappedBy: queryJob
      cascade: ["persist"]
  manyToOne:
    user:
      targetEntity: User
      inversedBy: queryJob
      joinColumns:
        user_id:
          referencedColumnName: id
