AppBundle\Entity\User:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    premium:
      type: boolean
      nullable: true
      options:
        default: false
    tid:
      type: string
      length: 255
      nullable: true
  oneToMany:
    query:
      targetEntity: AppBundle\Entity\Query
      mappedBy: user
    queryJob:
      targetEntity: AppBundle\Entity\QueryJob
      mappedBy: user
