AppBundle\Entity\User:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    premium:
      type: boolean
      nullable: true
      options:
        default: false
    tid:
      type: string
      length: 255
      nullable: true
    secret:
      type: string
      length: 255
      nullable: true
    token:
      type: string
      length: 255
      nullable: true
  oneToMany:
    query:
      targetEntity: Query
      mappedBy: user
    queryJob:
      targetEntity: QueryJob
      mappedBy: user
