Polls\MainBundle\Entity\Admin:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    username:
      type: string
      length: 150
      nullable: false
    password:
      type: string
      length: 255
      nullable: false
    salt:
      type: string
      length: 32
      nullable: false
